deploy_production:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  tags:
    - production
  only:
    refs:
    - tags
    - triggers
    - master
  when: manual
  before_script:
    - docker info
    - apk add --no-cache docker-compose git
    - echo CLIENT_URL="$CLIENT_URL" >> .env
    - echo REACT_APP_API_URL="$REACT_APP_API_URL" >> .env
    - echo REACT_APP_SECRET_KEY="$REACT_APP_SECRET_KEY" >> .env
    - echo REACT_APP_SECRET_IV="$REACT_APP_SECRET_IV" >> .env
    - cat .env
  script:
    - source .env
    # - git submodule sync --recursive
    # - git submodule update --init --recursive
    # - cp .env ./allgrownup/.env
    - docker-compose up --build -d
    # - docker-compose up -d
